version: 0.2
env:
  variables:
    S3_BUCKET: "cad.hardylabs.com"
phases:
  install:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod --aot
  post-build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
